site_name: “Cuddly Funicular”       # название сайта  
site_url: https://ktdtkpohhdj.github.io/cuddly-funicular/   # URL после деплоя (если используется GH Pages)

repo_url: https://github.com/ktdtkpohhdj/cuddly-funicular
edit_uri: blob/site

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]

nav:
  - Start: index.md
  - Example: example.md
  - Practice: practice.md
