name: Build and Deploy Documentation

on: 
    push:
        branches:
            - site


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Jekyll Site
        uses: helaili/jekyll-action@v2.2.2
        with:
            profile: github
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
            ACCESS_TOKEN: ${{ secret.ACCESS_TOKEN }}
            branch: gh-pages
            folder: _site
